FROM node:lts-alpine

RUN apk --no-cache add curl

RUN mkdir /app
WORKDIR /app
COPY package*.json .
COPY .npmrc .

RUN npm i
RUN npm i -g serve

COPY tsconfig.json .
COPY tsconfig.node.json .
COPY vite.config.ts .
COPY codegen.yml .
COPY index.html .

COPY public ./public
COPY src ./src

ARG VITE_REACT_APP_GRAPHQL_API_URL
ENV VITE_REACT_APP_GRAPHQL_API_URL ${VITE_REACT_APP_GRAPHQL_API_URL}

RUN npm run build

CMD serve -s dist