mutation CreateBonsai($data: BonsaiInput!) {
  createBonsai(data: $data) {
    id
    name
    specie {
      id
      name
    }
    age
    photo
    createdAt
    updatedAt
    repotting
    nextRepotting
    ligaturing
  }
}
