query GetBonsaiById($bonsaiId: Int!) {
  getBonsaiById(id: $bonsaiId) {
    name
    specie {
      id
      name
    }
    age
    photo
    repotting
    nextRepotting
    ligaturing
    deligaturing
  }
}
