query GetBonsaisByUser {
  getBonsaisByUser {
    id
    name
    specie {
      id
      name
    }
    age
    photo
    createdAt
    updatedAt
    repotting
    nextRepotting
    ligaturing
    deligaturing
  }
}
