query GetCurrentUser {
  getCurrentUser {
    id
    firstname
    email
    password
    role
    createdAt
    updatedAt
    bonsais {
      id
      name
      specie {
        name
      }
      age
      photo
      createdAt
      updatedAt
      repotting
      nextRepotting
      ligaturing
    }
  }
}
