mutation UpdateBonsai($data: UpdateBonsaiInput!, $bonsaiId: Int!) {
  updateBonsai(data: $data, id: $bonsaiId) {
    name
    species
    age
    photo
    repotting
    nextRepotting
    ligaturing
    deligaturing
  }
}
