mutation UpdateBonsai($data: UpdateBonsaiInput!, $updateBonsaiId: Int!) {
  updateBonsai(data: $data, id: $updateBonsaiId) {
    name
    age
    photo
    repotting
    nextRepotting
    ligaturing
    deligaturing
    specie {
      id
      name
    }
  }
}
